

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: First job
    steps:
    - bash: echo Build First job
      displayName: 'Run a one-line script'
  
- stage: Dev deploy
  jobs:
  - job: Dev deploy job
    steps:
    - bash: echo Dev deploy job
      displayName: 'Run a one-line script'

- stage: QA deploy
  jobs:
  - job: QA deploy job
    steps:
    - bash: echo QA deploy job
      displayName: 'Run a one-line script'

- stage: Prod deploy
  jobs:
  - job: Prod deploy job
    steps:
    - bash: echo Prod deploy job
      displayName: 'Run a one-line script'
      